import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPairSync,randomBytes} from 'node:crypto';
import {createRequire} from 'node:module';
import worker,{init,accept,dispatch,payload,validate} from '../cloud/worker.mjs';
import {titles,itemInfo} from '../cloud/style.mjs';
const require=createRequire(import.meta.url);const {signed,CloudQueue}=require('../companion/cloud');
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
function database(){
 const sql=new DatabaseSync(':memory:');
 const db={prepare(query){let params=[];return {bind(...args){params=args;return this;},async first(){return sql.prepare(query).get(...params)||null;},async all(){return {results:sql.prepare(query).all(...params)};},async run(){const r=sql.prepare(query).run(...params);return {meta:{changes:Number(r.changes)}};}};},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};return db;
}
const db=database();await init(db);const t=Math.floor(Date.now()/1000);
const event=(id,stamp=t)=>({id,player:'Test-Realm',kind:'loot',itemId:19019,itemName:'Test sword',quality:5,quantity:1,timestamp:stamp,level:0,test:false});
await db.prepare('INSERT INTO items VALUES(?,?,?)').bind(19019,JSON.stringify({name:'Thunderfury',quality:5,icon:'https://wow.zamimg.com/images/wow/icons/large/inv_sword_39.jpg'}),t).run();
const env={DB:db,DISCORD_WEBHOOK:'https://discord.com/api/webhooks/123/FakeTestToken'};
let sent=[];const sender=async(url,options)=>{sent.push(JSON.parse(options.body));await new Promise(r=>setTimeout(r,5));return new Response('{}',{status:200});};
await accept(db,[event('one'),event('one')]);
assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM events').first()).n,1);
await Promise.all([dispatch(env,sender,t),dispatch(env,sender,t)]);assert.equal(sent.length,1);
assert.ok(sent[0].embeds[0].thumbnail);assert.equal(sent[0].embeds[0].fields,undefined);assert.equal(sent[0].embeds[0].footer,undefined);
assert.ok(sent[0].embeds[0].description.includes('**Test** received'));
assert.ok(!sent[0].embeds[0].description.includes('Test-Realm'));
await accept(db,[event('one')]);await dispatch(env,sender,t+3);assert.equal(sent.length,1);
console.log('PASS concurrent relays, repeated event IDs, icons and clean message style');
await accept(db,[event('old1',t-86400),event('old2',t-86400)],t);
await dispatch(env,sender,t+119);assert.equal(sent.length,1);await dispatch(env,sender,t+121);assert.equal(sent.length,2);assert.equal(sent[1].embeds[0].title,'Guild catch-up');
assert.ok(sent[1].embeds[0].description.includes('**Test**:'));
assert.ok(!sent[1].embeds[0].description.includes('Test-Realm'));
await accept(db,[event('timeout',t+120)],t+122);
await dispatch(env,async()=>{throw new Error('lost response');},t+124);await dispatch(env,sender,t+128);
assert.equal((await db.prepare("SELECT state FROM events WHERE id='Test-Realm:timeout'").first()).state,'uncertain');assert.equal(sent.length,2);
console.log('PASS catch-up batching and ambiguous Discord response is not retried');
const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),id={id:randomBytes(16).toString('hex'),privateKey:pair.privateKey};
await db.prepare('INSERT INTO relays(id,jwk,admin) VALUES(?,?,1)').bind(id.id,JSON.stringify(pair.publicKey.export({format:'jwk'}))).run();
const calls=[];const bridge=async(url,options)=>worker.fetch(new Request(url,options),{DB:db},{waitUntil:p=>calls.push(p)});
const status=await signed('https://unit.workers.dev',id,'/status',{},bridge);assert.ok(status.counts);
await assert.rejects(()=>signed('https://unit.workers.dev',{...id,id:'a'.repeat(32)},'/status',{},bridge),/not registered/);
let res=await worker.fetch(new Request('https://unit.workers.dev/events',{method:'POST',body:'{}'}),{DB:db},{});assert.equal(res.status,401);
await signed('https://unit.workers.dev',id,'/settings',{settings:{minimumQuality:5,blockedItemIds:[19019],watchItemIds:[],botName:'Guild Herald'}},bridge);
assert.equal((await signed('https://unit.workers.dev',id,'/settings',{},bridge)).botName,'Guild Herald');
await accept(db,[event('blocked')]);assert.equal((await db.prepare("SELECT state FROM events WHERE id='Test-Realm:blocked'").first()).state,'filtered');
await accept(db,[{...event('personal-blue'),itemId:123,itemName:'Personal blue',quality:3},{...event('legacy-green'),itemId:124,itemName:'Legacy green',quality:2}]);
assert.equal((await db.prepare("SELECT state FROM events WHERE id='Test-Realm:personal-blue'").first()).state,'pending');
assert.equal((await db.prepare("SELECT state FROM events WHERE id='Test-Realm:legacy-green'").first()).state,'filtered');
const preview=await signed('https://unit.workers.dev',id,'/preview',{kind:'loot',itemId:19019},bridge);assert.equal(preview.queued,false);assert.equal(preview.payload.username,'Guild Herald');
assert.ok(!preview.payload.embeds[0].title.includes('TEST'));assert.equal(preview.payload.embeds[0].footer,undefined);
const level=await signed('https://unit.workers.dev',id,'/preview',{kind:'level',level:40},bridge);assert.ok(level.payload.embeds[0].description.includes('40'));assert.ok(level.payload.embeds[0].description.includes('LootTester'));
assert.ok(!level.payload.embeds[0].description.includes('ExampleRealm'));
const levelCards=[10,20,30,40,50,60].map(n=>payload([{body:JSON.stringify({...event('milestone-'+n),kind:'level',itemId:0,level:n})}],false));
assert.ok(levelCards.slice(0,5).every((card,i)=>card.embeds[0].title.includes(String((i+1)*10))));
assert.ok(levelCards[5].embeds[0].title.includes('Level 60'));
assert.ok(levelCards[5].content.includes('dinged 60'));
assert.ok(levelCards[5].embeds[0].description.includes("Maybe it's time to touch some grass?"));
assert.equal(levelCards[4].content,undefined);
const maxTest=await signed('https://unit.workers.dev',id,'/preview',{kind:'level',level:60},bridge);
assert.ok(maxTest.payload.content.includes('LootTester'));assert.ok(!JSON.stringify(maxTest.payload).includes('TEST'));
const catchup=await signed('https://unit.workers.dev',id,'/preview',{kind:'digest'},bridge);
assert.equal(catchup.payload.embeds[0].title,'Guild catch-up');
assert.ok(catchup.payload.embeds[0].description.includes('9 events from 3 players'));
assert.ok(!catchup.payload.embeds[0].description.includes('more)'));
const thirdLine=catchup.payload.embeds[0].description.split('\n').find(line=>line.startsWith('**LootTesterThree**:'));
assert.ok(thirdLine.indexOf('level 50')<thirdLine.indexOf('Melted Candle'));
assert.ok(!JSON.stringify(catchup.payload).includes('TEST'));
assert.equal(validate({...event('bad'),itemId:-1}),false);assert.equal(titles.length,9);assert.ok(titles.every(v=>v.length===12));
console.log('PASS signed relay access, shared filters, item and level previews without game');
const maxDb=database();await init(maxDb);
await accept(maxDb,[{...event('missed-max',t-86400),kind:'level',itemId:0,level:60}],t);
const maxPosts=[];await dispatch({...env,DB:maxDb},async(url,options)=>{maxPosts.push(JSON.parse(options.body));return new Response('{}',{status:200});},t);
assert.equal(maxPosts.length,1);assert.ok(maxPosts[0].embeds[0].title.includes('Level 60'));
assert.equal((await maxDb.prepare("SELECT state FROM events WHERE id='Test-Realm:missed-max'").first()).state,'sent');
console.log('PASS escalating level milestones, max-level standalone catch-up and synthetic digest preview');
const crowdedDb=database();await init(crowdedDb);
await accept(crowdedDb,Array.from({length:80},(_,i)=>({...event('crowded-'+i,t-86400),itemName:'Long named loot '+String(i)+' '+('A'.repeat(130))})),t);
const crowdedPosts=[];
for(let i=0;i<12;i++){
 await dispatch({...env,DB:crowdedDb},async(url,options)=>{crowdedPosts.push(JSON.parse(options.body));return new Response('{}',{status:200});},t+121+i*901);
 if((await crowdedDb.prepare("SELECT COUNT(*) AS n FROM events WHERE state='sent'").first()).n===80)break;
}
assert.equal((await crowdedDb.prepare("SELECT COUNT(*) AS n FROM events WHERE state='sent'").first()).n,80);
assert.ok(crowdedPosts.length>1);
assert.ok(crowdedPosts.every(post=>post.embeds[0].description.length<=3700&&!post.embeds[0].description.includes('more)')));
assert.equal(crowdedPosts.reduce((n,post)=>n+(post.embeds[0].description.match(/https:\/\/www\.wowhead\.com\/classic\/item=19019/g)||[]).length,0),80);
console.log('PASS long catch-up splits into complete messages without hiding any event');
const digestDb=database();await init(digestDb);
await digestDb.prepare('INSERT INTO relays(id,jwk,admin) VALUES(?,?,1)').bind(id.id,JSON.stringify(pair.publicKey.export({format:'jwk'}))).run();
const digestEnv={...env,DB:digestDb},digestWaits=[],digestPosts=[];
const digestBridge=async(url,options)=>worker.fetch(new Request(url,options),digestEnv,{waitUntil:p=>digestWaits.push(p)});
const realFetch=globalThis.fetch;
try {
 globalThis.fetch=async(url,options)=>{digestPosts.push(JSON.parse(options.body));return new Response('{}',{status:200});};
 await signed('https://unit.workers.dev',id,'/test',{kind:'digest',id:'digest-one'},digestBridge);
 await Promise.all(digestWaits);
 assert.equal(digestPosts.length,1);assert.equal(digestPosts[0].embeds[0].title,'Guild catch-up');
 await signed('https://unit.workers.dev',id,'/test',{kind:'digest',id:'digest-one'},digestBridge);
 await Promise.all(digestWaits);assert.equal(digestPosts.length,1);
 const sampleBody=(await digestDb.prepare("SELECT body FROM events WHERE id='test-digest:digest-one'").first()).body;
 await digestDb.prepare("INSERT INTO events(id,body,received,backlog,state) VALUES(?,?,?,1,'pending')").bind('test-digest:late',sampleBody,t-200).run();
 await dispatch(digestEnv,globalThis.fetch,t+3);
 assert.equal(digestPosts.length,2);assert.equal(digestPosts[1].embeds[0].title,'Guild catch-up');
} finally {globalThis.fetch=realFetch;}
console.log('PASS catch-up test posts once for a repeated test ID without a live Discord request');
const volunteer=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),other={id:randomBytes(16).toString('hex'),privateKey:volunteer.privateKey};
await signed('https://unit.workers.dev',id,'/relays',{registration:{id:other.id,publicKey:volunteer.publicKey.export({format:'jwk'})}},bridge);
assert.ok((await signed('https://unit.workers.dev',other,'/status',{},bridge)).counts);
await assert.rejects(()=>signed('https://unit.workers.dev',other,'/settings',{settings:{minimumQuality:0,blockedItemIds:[],watchItemIds:[]}},bridge),/administrator/);
await assert.rejects(()=>signed('https://unit.workers.dev',id,'/settings',{settings:{minimumQuality:0,blockedItemIds:[],watchItemIds:[],botName:'   '}},bridge),/Invalid filters/);
await signed('https://unit.workers.dev',id,'/relays',{revoke:other.id},bridge);
await assert.rejects(()=>signed('https://unit.workers.dev',other,'/status',{},bridge),/not registered/);
const badBody=async(url,options)=>bridge(url,{...options,body:options.body+' '});
await assert.rejects(()=>signed('https://unit.workers.dev',id,'/status',{},badBody),/not registered/);
const rateDb=database();await init(rateDb);await accept(rateDb,[{...event('rate-limit'),kind:'level',level:30,itemId:0}],t);
let rateCalls=0;const rateSender=async()=>{rateCalls++;return rateCalls===1?new Response('{"retry_after":5}',{status:429}):new Response('{}');};
await dispatch({...env,DB:rateDb},rateSender,t);await dispatch({...env,DB:rateDb},rateSender,t+4);assert.equal(rateCalls,1);
await dispatch({...env,DB:rateDb},rateSender,t+6);assert.equal(rateCalls,2);
assert.equal((await rateDb.prepare("SELECT state FROM events WHERE id='Test-Realm:rate-limit'").first()).state,'sent');
console.log('PASS relay approval/revocation, tamper rejection, administrator-only filters and Discord rate-limit retry');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lootbot-cloud-'));const file=path.join(dir,'queue.json');
const q=new CloudQueue(file,{url:'https://unit.workers.dev'},id);q.receive(event('queued'));await assert.rejects(()=>q.flush(async()=>{throw Error();}));
const restarted=new CloudQueue(file,{url:'https://unit.workers.dev'},id);assert.equal(await restarted.flush(bridge),1);assert.equal(restarted.data.entries['Test-Realm:queued'].state,'accepted');
restarted.receive(event('expired',t-31*86400));restarted.receive(event('fresh'));
assert.equal(await restarted.flush(bridge),1);
assert.equal(restarted.data.entries['Test-Realm:expired'].state,'expired');
assert.equal(restarted.data.entries['Test-Realm:fresh'].state,'accepted');
await Promise.all(calls);fs.unlinkSync(file);fs.rmdirSync(dir);
console.log('PASS persistent upload retry queue; all cloud tests passed (no live Discord calls)');
