CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY, body TEXT NOT NULL, received INTEGER NOT NULL, backlog INTEGER NOT NULL, state TEXT NOT NULL DEFAULT 'pending', batch TEXT);
CREATE INDEX IF NOT EXISTS pending_events ON events(state, backlog, received);
CREATE TABLE IF NOT EXISTS control (id INTEGER PRIMARY KEY, owner TEXT, lease INTEGER NOT NULL DEFAULT 0, last_digest INTEGER NOT NULL DEFAULT 0, next_send INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO control(id) VALUES(1);
CREATE TABLE IF NOT EXISTS relays (id TEXT PRIMARY KEY, jwk TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, admin INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS settings (id INTEGER PRIMARY KEY, body TEXT NOT NULL);
INSERT OR IGNORE INTO settings(id,body) VALUES(1,'{"minimumQuality":0,"watchItemIds":[],"blockedItemIds":[]}');
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY, body TEXT NOT NULL, updated INTEGER NOT NULL);
